### ISSUE TITLE
Wrapping exponents in braces breaks Maxima support

### ISSUE THREAD

**Issue by blipvert** [kpeeters/cadabra#1]
In commit f042aeea7cb150b6b9e94642ddc2601df10e9217 a change was made to the file `src/display.cc` to wrap exponents in a LaTeX grouping construct.  Unfortunately, this breaks Maxima support, because Maxima interprets braced expressions as sets.   For example:
`trigsimp( sin(x)**2 + cos(x)**2 ): @maxima(%);`
produces `(\sin(x))**{2} + (\cos(x))**{2}` rather than `1` as expected.

**Comment by kpeeters** [comment]
This is all done in a much more robust way in cadabra2, to be released soon (you can already see the repository at https://github.com/kpeeters/cadabra2 but there is no maxima support there yet, only sympy).

**Comment by blipvert** [comment]
I think, though, that this might easily be fixed by using parentheses instead of braces, at least when outputting to plain format.
