### ISSUE TITLE
Please explain how to build UI

### ISSUE THREAD

**Issue by yurivict** [kpeeters/cadabra#3]
Descriptions says '"Both a command-line and a graphical interface are available." But when I build it there is no graphics app. Is there supposed to be "xcadabra" built?

Please add to README how to build UI.

**Comment by Doxdrum** [comment]
I built Cadabra from the git source, and for calling the UI I use the icon in the menu. In xfce it is under the _Education_ tab.

Thanks to your question I just noticed that it seems that it cannot be called from the terminal. Good point!

**Comment by yurivict** [comment]
Could you please tell me what is the command that this icon calls?

**Comment by yurivict** [comment]
Ok, when gtkmm3 is installed, it builds cadabra-gtk

**Comment by kpeeters** [comment]
Note you posted this in the issue tracker for Cadabra 1.x. Closing.
